modLoader="javafml"
loaderVersion="[${loaderversion},)"
issueTrackerURL="https://github.com/McJtyMods/DeepResonance/issues"
authors="Elec332, McJty"

[[mods]]
modId="deepresonance"
version="${version}"
displayName="DeepResonance"
description="Power generation based on resonating crystals."

[[dependencies.deepresonance]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mcversion},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.deepresonance]]
    modId="forge"
    mandatory=true
    versionRange="[${forgeversion},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.deepresonance]]
    modId="eleccore"
    mandatory=true
    versionRange="[${coreversion},)"
    ordering="AFTER"
    side="BOTH"
	
[[dependencies.deepresonance]]
    modId="mcjtylib"
    mandatory=true
    versionRange="[${libversion},)"
    ordering="AFTER"
    side="BOTH"
	
[[dependencies.deepresonance]]
    modId="rftoolsbase"
    mandatory=false #Until maven is fixed
    versionRange="[${baseversion},)"
    ordering="AFTER"
    side="BOTH"
